services:
  api:
    extends:
      file: developers-italia-api/docker-compose.yml
      service: api
    env_file: ".env" # Must define PASETO_KEY
    environment:
      - GOFLAGS=-buildvcs=false

  db:
    extends:
      file: developers-italia-api/docker-compose.yml
      service: db
    volumes:
      - pgdata:/var/lib/postgresql/data

  crawler:
    build:
      context: ./publiccode-crawler
    depends_on:
      - api
    networks:
      - default
    env_file: ".env" # Must define PASETO_KEY and GITHUB_TOKEN
    environment:
      - API_BASEURL=http://api:3000/v1/
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}

  client:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - API_BASEURL=http://localhost:3000/v1
    depends_on:
      - api
    networks:
      - default
    ports:
      - "8081:8080"
volumes:
  pgdata:
