name: Build and publish helm chart

on:
  workflow_dispatch:
  push:
    paths:
      - 'charts/oss-catalog/**'

jobs:
  build_and_publish_helm_chart:
    name: Push helm chart to ghcr
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Package Helm Chart
        run: |
          helm dependency update ./charts/oss-catalog
          helm lint ./charts/oss-catalog
          helm package ./charts/oss-catalog

      - name: Check helm chart version on registry
        run: | 
          VERSION=$(helm show chart charts/oss-catalog | grep "^version:" | cut -d ':' -f 2)
          echo "Check chart with version v${VERSION} is not already on ghcr.io..."
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
          helm show chart oci://ghcr.io/${{ github.repository_owner }}/oss-catalog --version $VERSION > version.txt || true
          if [ -s version.txt ]; then
            echo "...chart version is already on ghcr.io."
            echo "version_on_registry=1" >> "$GITHUB_ENV"
          else
            echo "...version not on ghcr.io."
            echo "version_on_registry=0" >> "$GITHUB_ENV"
          fi        
          
      - name: Push Helm Chart
        # Publish chart only on changes on main branch and if version does not exist on registry.
        if: github.ref == 'refs/heads/main'
        run: | 
          if [ $version_on_registry != 0 ]; then
            echo "Failed: Chart version is already on ghcr.io!"
            exit 1
          fi
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
          helm push oss-catalog-chart-*.tgz oci://ghcr.io/${{ github.repository_owner }}/
